# vi: set ft=ruby

require 'rbconfig'

ROLE_NAME = 'bind'
HOST_NAME = 'test' + ROLE_NAME
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos71-nocm'
  config.vm.define HOST_NAME do |node|
    node.vm.hostname = HOST_NAME
    node.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'test.yml'         # Elaborate test that shows all features
      # ansible.playbook = 'test-bare.yml'  # Minimal test case
    end
  end
end

