# roles/bind/handlers/main.yml
---

- name: reload bind
  service:
    name: "{{ bind_service }}"
    state: reloaded

- name: restart bind
  service:
    name: "{{ bind_service }}"
    state: restarted
