---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:

    # Only collect network facts to reduce setup time
    - name: Gathering Facts
      setup:
        gather_subset:
          - 'network'

    - set_fact:
        local_dns: "{{ '@' + ansible_default_ipv4.address }}"

    - name: IPv4 Forward lookups
      assert:
        that:
          - lookup('dig', 'ns1.acme-inc.com', local_dns )    == '172.17.0.2'
          - lookup('dig', 'ns2.acme-inc.com', local_dns)     == '172.17.0.3'
          - lookup('dig', 'srv001.acme-inc.com', local_dns)  == '172.17.1.1'
          - lookup('dig', 'srv002.acme-inc.com', local_dns)  == '172.17.1.2'
          - lookup('dig', 'mail001.acme-inc.com', local_dns) == '172.17.2.1'
          - lookup('dig', 'mail002.acme-inc.com', local_dns) == '172.17.2.2'
          - lookup('dig', 'mail003.acme-inc.com', local_dns) == '172.17.2.3'
          - lookup('dig', 'srv010.acme-inc.com', local_dns)  == '10.0.0.10'
          - lookup('dig', 'srv011.acme-inc.com', local_dns)  == '10.0.0.11'
          - lookup('dig', 'srv012.acme-inc.com', local_dns)  == '10.0.0.12'
          - lookup('dig', 'srv001.example.com', local_dns)   == '192.0.2.1'
          - lookup('dig', 'srv002.example.com', local_dns)   == '192.0.2.2'
          - lookup('dig', 'mail001.example.com', local_dns)  == '192.0.2.10'

    - name: IPv4 Reverse lookups
      assert:
        that:
          - lookup('dig', '172.17.0.2/PTR', local_dns) == 'ns1.acme-inc.com.'
          - lookup('dig', '172.17.0.3/PTR', local_dns) == 'ns2.acme-inc.com.'
          - lookup('dig', '172.17.1.1/PTR', local_dns) == 'srv001.acme-inc.com.'
          - lookup('dig', '172.17.1.2/PTR', local_dns) == 'srv002.acme-inc.com.'
          - lookup('dig', '172.17.2.1/PTR', local_dns) == 'mail001.acme-inc.com.'
          - lookup('dig', '172.17.2.2/PTR', local_dns) == 'mail002.acme-inc.com.'
          - lookup('dig', '172.17.2.3/PTR', local_dns) == 'mail003.acme-inc.com.'
          - lookup('dig', '10.0.0.10/PTR', local_dns)  == 'srv010.acme-inc.com.'
          - lookup('dig', '10.0.0.11/PTR', local_dns)  == 'srv011.acme-inc.com.'
          - lookup('dig', '10.0.0.12/PTR', local_dns)  == 'srv012.acme-inc.com.'
          - lookup('dig', '192.0.2.1/PTR', local_dns)  == 'srv001.example.com.'
          - lookup('dig', '192.0.2.2/PTR', local_dns)  == 'srv002.example.com.'
          - lookup('dig', '192.0.2.10/PTR', local_dns) == 'mail001.example.com.'

    - name: IPv4 Alias lookups
      assert:
        that:
          - lookup('dig', 'www.acme-inc.com', local_dns)      == '172.17.1.1'
          - lookup('dig', 'mysql.acme-inc.com', local_dns)    == '172.17.1.2'
          - lookup('dig', 'smtp.acme-inc.com', local_dns)     == '172.17.2.1'
          - lookup('dig', 'mail-in.acme-inc.com', local_dns)  == '172.17.2.1'
          - lookup('dig', 'imap.acme-inc.com', local_dns)     == '172.17.2.3'
          - lookup('dig', 'mail-out.acme-inc.com', local_dns) == '172.17.2.3'
          - lookup('dig', 'www.example.com', local_dns)       == '192.0.2.1'

    - name: IPv6 Forward lookups
      assert:
        that:
          - lookup('dig', 'srv001.acme-inc.com/AAAA', local_dns)  == '2001:db8::1'
          - lookup('dig', 'srv002.acme-inc.com/AAAA', local_dns)  == '2001:db8::2'
          - lookup('dig', 'mail001.acme-inc.com/AAAA', local_dns) == '2001:db8::d:1'
          - lookup('dig', 'mail002.acme-inc.com/AAAA', local_dns) == '2001:db8::d:2'
          - lookup('dig', 'mail003.acme-inc.com/AAAA', local_dns) == '2001:db8::d:3'
          - lookup('dig', 'srv001.example.com/AAAA', local_dns)   == '2001:db9::1'

    - name: IPv6 Reverse lookups
      assert:
        that:
          - lookup('dig', '2001:db8::1/PTR', local_dns)   == 'srv001.acme-inc.com.'
          - lookup('dig', '2001:db8::2/PTR', local_dns)   == 'srv002.acme-inc.com.'
          - lookup('dig', '2001:db8::d:1/PTR', local_dns) == 'mail001.acme-inc.com.'
          - lookup('dig', '2001:db8::d:2/PTR', local_dns) == 'mail002.acme-inc.com.'
          - lookup('dig', '2001:db8::d:3/PTR', local_dns) == 'mail003.acme-inc.com.'
          - lookup('dig', '2001:db8::d:3/PTR', local_dns) == 'mail003.acme-inc.com.'
          - lookup('dig', '2001:db9::1/PTR', local_dns)   == 'srv001.example.com.'

    - name: NS records lookup
      assert:
        that:
          - lookup('dig', 'acme-inc.com/NS', local_dns).split(',') | sort | join(',') == 'ns1.acme-inc.com.,ns2.acme-inc.com.'
          - lookup('dig', 'example.com/NS', local_dns).split(',')  | sort | join(',') == 'ns1.acme-inc.com.,ns2.acme-inc.com.'

    - name: MX records lookup
      assert:
        that:
          - lookup('dig', 'acme-inc.com/MX', local_dns).split(',') | sort | join(',') == '10 mail001.acme-inc.com.,20 mail002.acme-inc.com.'
          - lookup('dig', 'example.com/MX', local_dns).split(',')  | sort | join(',') == '10 mail001.example.com.'

    - name: Service records lookup
      assert:
        that:
          - lookup('dig', '_ldap._tcp.acme-inc.com/SRV', local_dns) == '0 100 88 srv010.acme-inc.com.'

    - name: TXT records lookup
      assert:
        that:
          - lookup('dig', '_kerberos.acme-inc.com/TXT', local_dns) == 'KERBEROS.ACME-INC.COM'
          - lookup('dig', 'acme-inc.com/TXT', local_dns).split(',') | sort | join(',') == 'more text,some text'
