---
dependency:
  name: galaxy

driver:
  # Specifies the driver that should be used. Podman should also work
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  # Set name and hostname
  - &instance
    image: ${image:-debian}:${tag:-latest}
    name: ns4
    groups:
      - dns
    hostname: ns4
    docker_networks:
      - name: bind
        ipam_config:
          - subnet: "10.11.0.0/16"
            gateway: "10.11.0.254"
    networks:
      - name: bind
        ipv4_address: "10.11.0.4"
    privileged: true
    tty: true
    # Volumes to mount within the container. Important to enable systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"

  - <<: *instance
    name: ns5
    hostname: ns5
    groups:
      - dns
    networks:
      - name: bind
        ipv4_address: "10.11.0.5"

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent

# Runs the verify.yml playbook
verifier:
  name: ansible
