---
# Primary Configuration

bind_zones:
  # Primary server for domain example.com (use zone type autodetection)
  - name: 'example.com'
    primaries:
      - 10.11.0.1
    networks:
      - '192.0.2'
    ipv6_networks:
      - '2001:db9::/48'
    name_servers:
      - ns1.acme-inc.com.
      - ns2.acme-inc.com.
    hostmaster_email: admin
    hosts:
      - name: srv001
        ip: 192.0.2.1
        ipv6: '2001:db9::1'
        aliases:
          - www
      - name: srv002
        ip: 192.0.2.2
        ipv6: '2001:db9::2'
      - name: mail001
        ip: 192.0.2.10
        ipv6: '2001:db9::3'
    mail_servers:
      - name: mail001
        preference: 10
  # Primary server for domain acme-inc.com (specify zone type explicitly)
  - name: 'acme-inc.com'
    type: primary
    primaries:
      - 10.11.0.1
    networks:
      - '10.11'
    ipv6_networks:
      - '2001:db8::/48'
    name_servers:
      - ns1
      - ns2
    hosts:
      - name: ns1
        ip: 10.11.0.1
      - name: ns2
        ip: 10.11.0.2
      - name: srv001
        ip: 10.11.1.1
        ipv6: 2001:db8::1
        aliases:
          - www
      - name: srv002
        ip: 10.11.1.2
        ipv6: 2001:db8::2
        aliases:
          - mysql
      - name: mail001
        ip: 10.11.2.1
        ipv6: 2001:db8::d:1
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 10.11.2.2
        ipv6: 2001:db8::d:2
      - name: mail003
        ip: 10.11.2.3
        ipv6: 2001:db8::d:3
        aliases:
          - imap
          - mail-out
      - name: srv010
        ip: 10.11.0.10
      - name: srv011
        ip: 10.11.0.11
      - name: srv012
        ip: 10.11.0.12
    mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: srv010
    text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
      - name: '@'
        text:
          - 'some text'
          - 'more text'
  - name: 'rpz'
    create_reverse_zones: false
    response_policy: true
    primaries:
      - 10.11.0.1
    name_servers:
      - ns1.acme-inc.com.
      - ns2.acme-inc.com.
    hostmaster_email: admin
    hosts:
      - name: blackhole.example2.com
        ip: 1.2.3.5
        ipv6: '2001:db10::100'
