---
name: Ansible Molecule

on:  # yamllint disable-line rule:truthy
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  setup:
    name: Setup scenarios matrix
    runs-on: ubuntu-22.04
    outputs:
      scenarios: ${{ steps.matrix.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          JSON="["

          for s in $(find molecule -mindepth 1 -maxdepth 1 -type d -exec basename "{}" \;); do
            JSON="${JSON}\"${s}\","
          done

          JSON="${JSON%?}"
          JSON="$JSON]"

          echo "::set-output name=scenarios::$(echo $JSON)"

  lint:
    name: Lint
    needs:
      - setup
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          command: lint
          scenario: ${{ fromJson(needs.setup.outputs.scenarios)[0] }}

  test:
    name: Scenario "${{ matrix.scenario }}" on ${{ matrix.config.image }}:${{ matrix.config.tag }}
    needs:
      - lint
      - setup
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.setup.outputs.scenarios) }}
        config:
          - name: debian11
            image: "debian"
            tag: "11"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule==4.0.2 molecule-docker==1.1.0 yamllint ansible-lint docker==6.0.1 netaddr dnspython

      - name: molecule
        run: molecule test --all
        env:
          image: ${{ matrix.config.image }}
          name: ${{ matrix.config.name }}
