---
name: Ansible Molecule

on:  # yamllint disable-line rule:truthy
  push:
    tags_ignore:
      - '*'
  pull_request:


jobs:
  test:
    name: Scenario "${{ matrix.distro }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule==4.0.2 molecule-plugins[docker] yamllint ansible-lint docker netaddr dnspython

      - name: Run Molecule Primary/Secondary/Forwarder tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests
        run: molecule test --scenario-name shared_inventory
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
